export const hotelTypes = [
  "Business",
  "Luxury",
  "Economic",
  "Family",
  "Single",
  "Romatic",
  "Dating",
  "Family Luxury",
  "Beach Resort",
  "Resort",
  "Mini",
  "Motel",
  "Flat",
  "Self-contain",
  "Presidential",
  "freeway",
  "Luxury apartment",
  "First Class",
  "Boutique",
  "Classic",
];

export const hotelFacilities = [
  "Family Class",
  "Outdoor Pool",
  "Fitness Center",
  "Beach Embedded",
  "WiFi included",
  "Golf club",
  "Spa",
  "Shooting Range",
  "Virtual Games",
  "Tennis and Snokers",
  "Swimming Pool",
  "Cinema",
];
